# Generated by Django 5.0.4 on 2024-06-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudor', '0002_alter_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='password',
        ),
    ]
